FROM python:3.10

RUN pip install fastapi
RUN pip install uvicorn

ENV PORT 2155
ENV HOST "0.0.0.0"

EXPOSE 2155

WORKDIR /app

COPY . /app

CMD ["uvicorn", "main:application", "--host", "0.0.0.0", "--port", "2155"]